version: '3.1'

services:
  db:
    container_name: database
    image: postgres
    env_file:
      - ".env.dist"
    environment:
      POSTGRES_PASSWORD: $PG_PASSWORD
      POSTGRES_DB: $DATABASE
    restart: always
    ports:
      - 5432:5432
    networks:
      - botnet
  tgbot:
    container_name: bot
    build:
      context: .
    command: python app.py
    volumes:
      - .:/src
    networks:
      - botnet
    restart: always
    env_file:
      - ".env.dist"
    depends_on:
      - db
      - admin
  admin:
    container_name: django_admin
    build:
      context: .
    command: python django_app.py runserver 0.0.0.0:8000 --noreload
    ports:
      - 8000:8000
    networks:
      - botnet
    restart: always
    env_file:
      - ".env.dist"
    depends_on:
      - db

networks:
  botnet:
    driver: bridge
