# Generated by Django 3.2 on 2021-05-03 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0003_alter_purchase_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='phone_number',
            field=models.IntegerField(null=True, verbose_name='Номер телефона'),
        ),
    ]
