# Generated by Django 3.2 on 2021-05-05 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0006_basket'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='user_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='referral',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referrer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersmanage.user'),
        ),
    ]
