# Generated by Django 3.2 on 2021-05-05 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0007_auto_20210505_1735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='referrer_id',
        ),
        migrations.AddField(
            model_name='referral',
            name='referral_id',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='referral',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersmanage.user'),
        ),
    ]
