# Generated by Django 3.2 on 2021-05-05 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0008_auto_20210505_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='user_id',
        ),
        migrations.AddField(
            model_name='referral',
            name='referrer_id',
            field=models.IntegerField(default=1, verbose_name='ID Реферера'),
            preserve_default=False,
        ),
    ]
