# Generated by Django 3.2 on 2021-05-07 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0010_auto_20210507_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='photo',
            field=models.CharField(max_length=300, verbose_name='Id фото товара'),
        ),
    ]
