# Generated by Django 3.2 on 2021-05-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0013_auto_20210509_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='item_id',
            field=models.IntegerField(max_length=100, verbose_name='ID товара'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='user_id',
            field=models.BigIntegerField(max_length=100, verbose_name='ID покупателя в TG'),
        ),
    ]
