# Generated by Django 3.2 on 2021-05-17 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0014_auto_20210509_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='item_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usersmanage.items', verbose_name='ID товара'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='user_id',
            field=models.ForeignKey(on_delete=models.SET(0), to='usersmanage.user', verbose_name='Id Пользователя в ТГ'),
        ),
    ]
