# Generated by Django 3.2 on 2021-05-19 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usersmanage', '0015_auto_20210517_1830'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Basket',
        ),
    ]
